export const tags = [
  { value: 'apple', label: 'Apple', count: 10 },
  { value: 'banana', label: 'Banana', count: 20 },
  { value: 'cherry', label: 'Cherry', count: 30 },
  { value: 'date', label: 'Date', count: 40 },
  { value: 'elderberry', label: 'Elderberry', count: 50 },
  { value: 'fig', label: 'Fig', count: 60 },
  { value: 'grape', label: 'Grape', count: 70 },
  { value: 'honeydew', label: 'Honeydew', count: 80 },
  { value: 'kiwi', label: 'Kiwi', count: 90 },
  { value: 'lemon', label: 'Lemon', count: 100 },
  { value: 'mango', label: 'Mango', count: 110 },
  { value: 'nectarine', label: 'Nectarine', count: 120 },
  { value: 'orange', label: 'Orange', count: 130 },
  { value: 'pear', label: 'Pear', count: 140 },
  { value: 'quince', label: 'Quince', count: 150 },
  { value: 'raspberry', label: 'Raspberry', count: 160 },
  { value: 'strawberry', label: 'Strawberry', count: 170 },
  { value: 'tangerine', label: 'Tangerine', count: 180 },
  { value: 'ugli', label: 'Ugli fruit', count: 190 },
  { value: 'vanilla', label: 'Vanilla bean', count: 200 },
  { value: 'watermelon', label: 'Watermelon', count: 210 },
  { value: 'xylophone', label: 'Xylophone (well, why not?)', count: 220 },
  { value: 'yellow squash', label: 'Yellow squash', count: 230 },
  { value: 'zucchini', label: 'Zucchini', count: 240 },
  { value: 'apricot', label: 'Apricot', count: 250 },
  { value: 'blackberry', label: 'Blackberry', count: 260 },
  { value: 'cantaloupe', label: 'Cantaloupe', count: 270 },
  { value: 'dragonfruit', label: 'Dragonfruit', count: 280 },
  { value: 'elderflower', label: 'Elderflower', count: 290 },
  { value: 'fig', label: 'Fig', count: 300 },
];
